---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: xxx-xxx-stable
  name: xxx-xxx
data:
  appMode: stable
  server.yaml: |+
    ---
    name: xxx-xxx
    mode: stable
    transport:
      http:
        port: 8889
        ip: '0.0.0.0'
      grpc:
        port: 50051
        ip: '0.0.0.0'

  log.yaml: |+
    ---
    file_path: "/home/log/go/xxx_xxx"
    prefix: ''

  mysql.yaml: |+
    ---
    

  redis.yaml: |+
    ---

  grpc_client.yaml: |+
    ---

